# Generated by Django 3.0.7 on 2020-08-11 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0003_auto_20200811_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_image', models.ImageField(blank=True, upload_to='')),
                ('service_name', models.CharField(blank=True, max_length=50)),
                ('service_describe', models.CharField(blank=True, max_length=100)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mart.Seller')),
            ],
        ),
    ]
