# Generated by Django 3.0.7 on 2020-08-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0004_seller_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_product',
            name='product_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
