# Generated by Django 3.0.7 on 2020-08-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0005_auto_20200814_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_product',
            name='product_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='seller_product',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seller_product',
            name='product_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
