# Generated by Django 3.0.7 on 2020-08-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0007_auto_20200814_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_product',
            name='product_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
