# Generated by Django 3.0.7 on 2020-08-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0008_auto_20200814_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_product',
            name='product_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='seller_product',
            name='product_price',
            field=models.IntegerField(blank=True),
        ),
    ]
