# Generated by Django 3.0.7 on 2020-08-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0009_auto_20200814_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_service',
            name='service_describe',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
